/**
 * @fileoverview Benchmark configuration for the BKR reification benchmark.
 *
 * This wires together, for each RDF reification pattern:
 *  - the CONSTRUCT mappers that expose the RDF 1.1 data as an RDF 1.2 view, and
 *  - the materialized RDF 1.1 dataset produced by `data/run-conversion.sh`.
 *
 * The SPARQL 1.2 user queries come from `queries/BKR-star_*.rq` and are fed to the
 * rewriter verbatim: the parser desugars their `<< s p o >>` reifier syntax into the
 * `rdf:reifies <<( s p o )>>` triple-term form itself, so no pre-conversion is needed.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  bkrNonReificationConstruct,
  bkrNonSingletonConstruct,
  bkrReificationConstruct,
  singletonPropertyConstruct,
} from '../queryConsts.js';
import type { BenchCase } from './runner.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const BKR_ROOT = join(HERE, '..', 'statics', 'REF-Benchmark', 'BKR');
const QUERY_DIR = join(BKR_ROOT, 'queries');
const DATA_DIR = join(BKR_ROOT, 'data');

/** A reification pattern: how RDF 1.2 statements are materialized in RDF 1.1. */
export interface PatternConfig {
  /** Pattern id used in case ids and reporting. */
  name: string;
  /** CONSTRUCT mappers (RDF 1.1 -> RDF 1.2 view) for this pattern. */
  mappers: string[];
  /** Materialized RDF 1.1 dataset filename under `data/`. */
  dataFile: string;
  /**
   * Filename prefix of the hand-written "baseline" queries written directly
   * against this pattern's RDF 1.1 materialization (e.g. `BKR-R` for classic
   * reification, `BKR-S` for singleton properties). These are the "original
   * query on the original data" the rewriting approach is compared against.
   */
  baselinePrefix: string;
}

/**
 * The reification patterns the benchmark can exercise. Each corresponds to one of
 * the datasets generated by `data/mapBkrStar.ts` / `run-conversion.sh`.
 */
export const PATTERNS: Record<string, PatternConfig> = {
  reification: {
    name: 'reification',
    mappers: [ bkrReificationConstruct, bkrNonReificationConstruct ],
    dataFile: 'BKR-Reification.ttl',
    baselinePrefix: 'BKR-R',
  },
  singleton: {
    name: 'singleton',
    mappers: [ singletonPropertyConstruct, bkrNonSingletonConstruct ],
    dataFile: 'BKR-Singleton.ttl',
    baselinePrefix: 'BKR-S',
  },
};

/** Reads a query file verbatim. */
export function loadRawQuery(fileName: string): string {
  return readFileSync(join(QUERY_DIR, fileName), 'utf8');
}

/**
 * Lists the BKR-star query file names (e.g. `BKR-star_A-Q1.rq`) that only contain
 * SELECT queries the rewriter can currently handle. Optionally filtered by a
 * predicate on the raw query text.
 */
export function listStarQueryFiles(filter?: (raw: string) => boolean): string[] {
  return readdirSync(QUERY_DIR)
    .filter(name => /^BKR-star_.*\.rq$/u.test(name))
    .filter((name) => {
      const raw = readFileSync(join(QUERY_DIR, name), 'utf8');
      return /select/iu.test(raw) && (filter ? filter(raw) : true);
    })
    .sort();
}

/**
 * Builds benchmark cases for the given pattern by pairing every BKR-star SELECT
 * query with that pattern's mappers, its materialized dataset, and the parallel
 * hand-written baseline query.
 *
 * The SPARQL 1.2 `<< s p o >>` reifier syntax is fed to the rewriter verbatim:
 * the parser desugars it into the `rdf:reifies <<( s p o )>>` triple-term form, so
 * no textual pre-conversion is needed.
 *
 * @param patternName - Key into {@link PATTERNS}.
 * @param materializedFile - Optional path to the RDF 1.1 dataset (or a subset) to
 *   run against. Defaults to the full dataset under `data/`.
 * @param queryFilter - Optional predicate to restrict which query files are used.
 */
export function buildCases(
  patternName: keyof typeof PATTERNS,
  materializedFile?: string,
  queryFilter?: (raw: string) => boolean,
): BenchCase[] {
  const pattern = PATTERNS[patternName];
  const file = materializedFile ?? join(DATA_DIR, pattern.dataFile);
  return listStarQueryFiles(queryFilter).map((fileName) => {
    const stem = fileName.replace(/^BKR-star_/u, '').replace(/\.rq$/u, '');
    const id = `${pattern.name}/${stem}`;
    const baselineFile = `${pattern.baselinePrefix}_${stem}.rq`;
    return {
      id,
      pattern: pattern.name,
      mappers: pattern.mappers,
      userQuery12: loadRawQuery(fileName),
      baselineQuery: existsSync(join(QUERY_DIR, baselineFile)) ?
        loadRawQuery(baselineFile) :
        undefined,
      materialized: { name: pattern.dataFile, file },
    };
  });
}

export { DATA_DIR, QUERY_DIR };
