/**
 * @fileoverview Turns the benchmark results JSON into a collection of SVG figures.
 *
 * Produces, per reification scheme × engine, comparing five approaches — the
 * standard rewriting, the same rewriting with {@link removeProjections} applied
 * (anonymizing hidden sub-`SELECT` variables and flattening the nested projections
 * away), the same rewriting with {@link pushDownAssertions} applied ("assertion
 * pushdown" — pushes `FILTER(sameTerm(?x, c))` constraints down into the triple
 * patterns that use them instead of matching generically and filtering afterwards),
 * the pushdown pipeline plus {@link pullUpExtends} applied twice (floats the `BIND`s
 * the pushdown leaves at every leaf back up to where they cost less, or drops them),
 * and the hand-written materialized baseline query:
 *   - time-by-query bar chart at the largest scale with data,
 *   - a scaling line chart (median time vs dataset size) per approach,
 *   - a rewriting-overhead bar chart (each rewriting variant / materialized ratio), and
 *   - a correctness heat-strip per checkable approach (does it agree with the case's
 *     reference answer — the hand-written `materialized` baseline?).
 *
 * **Censoring.** A query that hits the time budget has no measurement, only a lower
 * bound: it took *at least* `timeoutMs`. Dropping those rows, as this script used to,
 * makes every chart lie in the same direction — the slowest runs are exactly the ones
 * that vanish, so an approach looks better the more often it fails, and a scaling line
 * can fall as the dataset grows because a query dropped out of the sum. They are drawn
 * instead at the budget, hatched and marked `≥`, and any aggregate containing one is
 * itself a lower bound (dashed).
 *
 * SVG is generated by hand so the script has no external dependencies.
 *
 * Usage:  node test/bench/plot.mjs [resultsJson] [outDir]
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const resultsJson = process.argv[2] ?? join(HERE, 'results', 'results.json');
const outDir = process.argv[3] ?? join(HERE, 'results', 'figures');
mkdirSync(outDir, { recursive: true });

const rows = JSON.parse(readFileSync(resultsJson, 'utf8'));

const COLORS = {
  rewriting: '#2b7bba',
  'rewriting+removeProjections': '#7a52c7',
  'rewriting+pushDownAssertions': '#17a398',
  'rewriting+pullUpExtends': '#c0399f',
  materialized: '#e08214',
  grid: '#cccccc',
  text: '#222222',
};
/** The four rewriting pipeline variants, compared against each other and against `materialized`. */
const REWRITING_APPROACHES = [
  'rewriting',
  'rewriting+removeProjections',
  'rewriting+pushDownAssertions',
  'rewriting+pullUpExtends',
];
const esc = s => String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');

/**
 * What a row contributes to a time chart, and whether that is a real measurement.
 * A `timeout` row contributes its budget as a *lower* bound; an `error` row contributes
 * nothing, since a query that could not run says nothing about how long it would take.
 */
function timing(row) {
  if (row.status === 'ok' && row.medianMs >= 0) {
    return { ms: row.medianMs, censored: false };
  }
  if (row.status === 'timeout') {
    return { ms: row.timeoutMs ?? 0, censored: true };
  }
  return null;
}

/** Diagonal hatch, referenced as `fill="url(#hatch)"`, marking a censored (>= budget) bar. */
const HATCH_DEF = `<defs><pattern id="hatch" width="6" height="6" patternTransform="rotate(45)" patternUnits="userSpaceOnUse"><rect width="6" height="6" fill="white" fill-opacity="0.55"/><line x1="0" y1="0" x2="0" y2="6" stroke="white" stroke-width="3"/></pattern></defs>`;

/** A bar, hatched and capped with a `≥` when the value is only a lower bound. */
function bar(x, y, width, height, color, censored, title) {
  const rect = `<rect x="${x}" y="${y}" width="${width}" height="${height}" fill="${color}">` +
    `<title>${title}</title></rect>`;
  if (!censored) {
    return rect;
  }
  return `${rect}<rect x="${x}" y="${y}" width="${width}" height="${height}" fill="url(#hatch)" ` +
    `pointer-events="none"/><text x="${x + width / 2}" y="${y - 3}" text-anchor="middle" font-size="10" ` +
    `fill="${COLORS.text}">≥</text>`;
}

function svgDoc(width, height, body) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" font-family="sans-serif" font-size="12">
<rect width="${width}" height="${height}" fill="white"/>
${HATCH_DEF}
${body}
</svg>`;
}

function legend(x, y, items) {
  return items.map((it, i) => `
<rect x="${x}" y="${y + i * 18}" width="12" height="12" fill="${it.color}"/>
<text x="${x + 18}" y="${y + i * 18 + 11}" fill="${COLORS.text}">${esc(it.label)}</text>`).join('');
}

const schemes = [ ...new Set(rows.map(r => r.scheme)) ];
const engines = [ ...new Set(rows.map(r => r.engine)) ];
const scaleOrder = [ 'xs', 's', 'm', 'l', 'xl' ];
const sortScales = arr => arr.sort((a, b) => scaleOrder.indexOf(a) - scaleOrder.indexOf(b));

/**
 * The largest scale that has at least one plottable row — a measurement or a censored
 * lower bound — e.g. so an engine that only fails to *load* bigger scales still gets a
 * "time by query" / "overhead" figure at the largest scale it could actually run,
 * instead of silently emitting nothing. Falls back to the largest configured scale.
 */
function largestScaleWithData(data, scales) {
  const withData = sortScales([ ...new Set(data.filter(timing).map(r => r.scale)) ]);
  return withData.at(-1) ?? scales.at(-1);
}

/** Grouped bar chart of median time per query for two approaches, at one scale. */
function timeByQuery(scheme, engine) {
  const rowsForEngine = rows.filter(r => r.engine === engine && r.scheme === scheme);
  const scales = sortScales([ ...new Set(rowsForEngine.map(r => r.scale)) ]);
  const scale = largestScaleWithData(rowsForEngine, scales);
  const data = rowsForEngine.filter(r => r.scale === scale && timing(r));
  const cases = [ ...new Set(data.map(r => r.caseId)) ].sort();
  if (cases.length === 0) {
    return null;
  }
  const maxMs = Math.max(1, ...data.map(r => timing(r).ms));
  const W = 900;
  const H = 460;
  const padL = 60;
  const padB = 90;
  const padT = 50;
  const padR = 20;
  const plotW = W - padL - padR;
  const plotH = H - padT - padB;
  const groupW = plotW / cases.length;
  const approaches = [ ...REWRITING_APPROACHES, 'materialized' ];
  const barW = Math.min(22, groupW / (approaches.length + 1));

  let body = `<text x="${W / 2}" y="24" text-anchor="middle" font-size="16" fill="${COLORS.text}">` +
    `${esc(scheme)} / ${esc(engine)} — median query time by query (scale ${esc(scale)})</text>`;
  // Y axis grid
  for (let g = 0; g <= 4; g++) {
    const y = padT + plotH - (plotH * g) / 4;
    const val = Math.round((maxMs * g) / 4);
    body += `<line x1="${padL}" y1="${y}" x2="${W - padR}" y2="${y}" stroke="${COLORS.grid}"/>` +
      `<text x="${padL - 6}" y="${y + 4}" text-anchor="end" fill="${COLORS.text}">${val}</text>`;
  }
  body += `<text x="16" y="${padT + plotH / 2}" transform="rotate(-90 16 ${padT + plotH / 2})" ` +
    `text-anchor="middle" fill="${COLORS.text}">median ms</text>`;

  for (const [ i, caseId ] of cases.entries()) {
    const gx = padL + i * groupW;
    for (const [ j, ap ] of approaches.entries()) {
      const rec = data.find(r => r.caseId === caseId && r.approach === ap);
      if (!rec) {
        continue;
      }
      const { ms, censored } = timing(rec);
      const h = (ms / maxMs) * plotH;
      const x = gx + groupW / 2 - (approaches.length * barW) / 2 + j * barW;
      const title = censored ?
        `${esc(caseId)} ${ap}: timed out, ≥${ms}ms` :
        `${esc(caseId)} ${ap}: ${ms}ms, rows=${rec.count}`;
      body += bar(x, padT + plotH - h, barW - 2, h, COLORS[ap], censored, title);
    }
    const label = caseId.split('/').at(-1);
    body += `<text x="${gx + groupW / 2}" y="${padT + plotH + 14}" text-anchor="end" ` +
      `transform="rotate(-40 ${gx + groupW / 2} ${padT + plotH + 14})" fill="${COLORS.text}">${esc(label)}</text>`;
  }
  body += legend(W - 160, padT, approaches.map(a => ({ color: COLORS[a], label: a })));
  body += `<text x="${W - 160}" y="${padT + approaches.length * 18 + 12}" font-size="10" ` +
    `fill="${COLORS.text}">hatched ≥ : timed out, lower bound</text>`;
  return svgDoc(W, H, body);
}

/**
 * Line chart: median time vs dataset size (quads) per approach, summed over queries.
 * A scale whose sum includes a timed-out query is a lower bound, so the segment leading
 * into it is dashed and its marker hollow — without that, an approach that starts failing
 * at a larger scale would appear to get *faster* as the dataset grows.
 */
function scaling(scheme, engine) {
  const data = rows.filter(r => r.engine === engine && r.scheme === scheme && timing(r));
  const scales = sortScales([ ...new Set(data.map(r => r.scale)) ]);
  if (scales.length < 2) {
    return null;
  }
  const approaches = [ ...REWRITING_APPROACHES, 'materialized' ];
  const points = {};
  const xByScale = {};
  for (const scale of scales) {
    const q = data.find(r => r.scale === scale)?.quads ?? 0;
    xByScale[scale] = q;
  }
  for (const ap of approaches) {
    points[ap] = scales.map((scale) => {
      const recs = data.filter(r => r.scale === scale && r.approach === ap);
      const timings = recs.map(timing);
      const total = timings.reduce((s, m) => s + m.ms, 0);
      const censored = timings.filter(m => m.censored).length;
      return { x: xByScale[scale], y: total, scale, censored, n: timings.length };
    });
  }
  const allX = Object.values(xByScale);
  const maxX = Math.max(...allX);
  const minX = Math.min(...allX);
  const maxY = Math.max(1, ...approaches.flatMap(a => points[a].map(p => p.y)));
  const W = 760;
  const H = 440;
  const padL = 70;
  const padB = 60;
  const padT = 50;
  const padR = 20;
  const plotW = W - padL - padR;
  const plotH = H - padT - padB;
  const sx = x => padL + (maxX === minX ? plotW / 2 : ((x - minX) / (maxX - minX)) * plotW);
  const sy = y => padT + plotH - (y / maxY) * plotH;

  let body = `<text x="${W / 2}" y="24" text-anchor="middle" font-size="16" fill="${COLORS.text}">` +
    `${esc(scheme)} / ${esc(engine)} — total query time vs dataset size</text>`;
  for (let g = 0; g <= 4; g++) {
    const y = padT + plotH - (plotH * g) / 4;
    body += `<line x1="${padL}" y1="${y}" x2="${W - padR}" y2="${y}" stroke="${COLORS.grid}"/>` +
      `<text x="${padL - 6}" y="${y + 4}" text-anchor="end" fill="${COLORS.text}">${Math.round((maxY * g) / 4)}</text>`;
  }
  for (const scale of scales) {
    const x = sx(xByScale[scale]);
    body += `<text x="${x}" y="${padT + plotH + 18}" text-anchor="middle" fill="${COLORS.text}">` +
      `${esc(scale)}\n</text>` +
      `<text x="${x}" y="${padT + plotH + 32}" text-anchor="middle" font-size="10" fill="${COLORS.text}">` +
      `${(xByScale[scale] / 1e6).toFixed(2)}M</text>`;
  }
  body += `<text x="${W / 2}" y="${H - 6}" text-anchor="middle" fill="${COLORS.text}">dataset size (quads)</text>`;
  body += `<text x="18" y="${padT + plotH / 2}" transform="rotate(-90 18 ${padT + plotH / 2})" ` +
    `text-anchor="middle" fill="${COLORS.text}">total median ms</text>`;
  for (const ap of approaches) {
    // One segment at a time: a segment is dashed when either end is a lower bound, so
    // the eye never reads a censored total as a measured one.
    for (const [ i, p ] of points[ap].entries()) {
      const prev = points[ap][i - 1];
      if (prev) {
        const bound = prev.censored > 0 || p.censored > 0;
        body += `<path d="M${sx(prev.x)},${sy(prev.y)} L${sx(p.x)},${sy(p.y)}" fill="none" ` +
          `stroke="${COLORS[ap]}" stroke-width="2"${bound ? ' stroke-dasharray="5 3"' : ''}/>`;
      }
      const title = p.censored > 0 ?
        `${ap} ${p.scale}: ≥${p.y}ms (${p.censored}/${p.n} queries timed out)` :
        `${ap} ${p.scale}: ${p.y}ms (${p.n} queries)`;
      body += `<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="3.5" ` +
        `fill="${p.censored > 0 ? 'white' : COLORS[ap]}" stroke="${COLORS[ap]}" stroke-width="1.5">` +
        `<title>${title}</title></circle>`;
    }
  }
  body += legend(padL + 10, padT, approaches.map(a => ({ color: COLORS[a], label: a })));
  body += `<text x="${padL + 10}" y="${padT + approaches.length * 18 + 12}" font-size="10" ` +
    `fill="${COLORS.text}">dashed / hollow: sum includes a timed-out query (lower bound)</text>`;
  return svgDoc(W, H, body);
}

/**
 * Grouped bar chart of overhead ratio (each rewriting variant's time / materialized
 * time) per query, at the largest scale with data. One bar group per query, one bar
 * per rewriting variant that has data. A ratio built from a censored value is itself
 * only a bound, and is hatched: `≥` when the numerator timed out, and skipped entirely
 * when the *denominator* did, since a baseline that timed out gives a ratio no
 * direction at all.
 */
function overhead(scheme, engine) {
  const rowsForEngine = rows.filter(r => r.engine === engine && r.scheme === scheme);
  const scales = sortScales([ ...new Set(rowsForEngine.map(r => r.scale)) ]);
  const scale = largestScaleWithData(rowsForEngine, scales);
  const data = rowsForEngine.filter(r => r.scale === scale);
  const cases = [ ...new Set(data.map(r => r.caseId)) ].sort();
  const ratios = cases.flatMap(caseId => REWRITING_APPROACHES.map((ap) => {
    const rw = timing(data.find(r => r.caseId === caseId && r.approach === ap) ?? {});
    const mt = timing(data.find(r => r.caseId === caseId && r.approach === 'materialized') ?? {});
    if (!rw || !mt || mt.censored || mt.ms <= 0) {
      return { caseId, approach: ap, ratio: null };
    }
    return { caseId, approach: ap, ratio: rw.ms / mt.ms, censored: rw.censored };
  })).filter(r => r.ratio !== null);
  if (ratios.length === 0) {
    return null;
  }
  const maxR = Math.max(1.2, ...ratios.map(r => r.ratio));
  const W = 900;
  const H = 440;
  const padL = 60;
  const padB = 90;
  const padT = 50;
  const padR = 20;
  const plotW = W - padL - padR;
  const plotH = H - padT - padB;
  const bw = plotW / cases.length;
  const barW = Math.min(24, bw / (REWRITING_APPROACHES.length + 1));

  let body = `<text x="${W / 2}" y="24" text-anchor="middle" font-size="16" fill="${COLORS.text}">` +
    `${esc(scheme)} / ${esc(engine)} — rewriting overhead (rewriting variant / materialized time, scale ${esc(scale)})</text>`;
  for (let g = 0; g <= 4; g++) {
    const y = padT + plotH - (plotH * g) / 4;
    body += `<line x1="${padL}" y1="${y}" x2="${W - padR}" y2="${y}" stroke="${COLORS.grid}"/>` +
      `<text x="${padL - 6}" y="${y + 4}" text-anchor="end" fill="${COLORS.text}">${((maxR * g) / 4).toFixed(1)}x</text>`;
  }
  // Reference line at ratio = 1
  const y1 = padT + plotH - (1 / maxR) * plotH;
  body += `<line x1="${padL}" y1="${y1}" x2="${W - padR}" y2="${y1}" stroke="#d62728" stroke-dasharray="4"/>`;
  for (const [ i, caseId ] of cases.entries()) {
    const gx = padL + i * bw;
    for (const [ j, ap ] of REWRITING_APPROACHES.entries()) {
      const r = ratios.find(rr => rr.caseId === caseId && rr.approach === ap);
      if (!r) {
        continue;
      }
      const h = (r.ratio / maxR) * plotH;
      const x = gx + bw / 2 - (REWRITING_APPROACHES.length * barW) / 2 + j * barW;
      body += bar(
        x,
        padT + plotH - h,
        barW - 2,
        h,
        COLORS[ap],
        r.censored,
        `${esc(caseId)} ${ap}: ${r.censored ? '≥' : ''}${r.ratio.toFixed(2)}x`,
      );
    }
    const label = caseId.split('/').at(-1);
    body += `<text x="${gx + bw / 2}" y="${padT + plotH + 14}" text-anchor="end" ` +
      `transform="rotate(-40 ${gx + bw / 2} ${padT + plotH + 14})" fill="${COLORS.text}">${esc(label)}</text>`;
  }
  body += legend(W - 190, padT, REWRITING_APPROACHES.map(a => ({ color: COLORS[a], label: a })));
  body += `<text x="${W - 190}" y="${padT + REWRITING_APPROACHES.length * 18 + 12}" font-size="10" ` +
    `fill="${COLORS.text}">hatched ≥ : timed out, lower bound</text>`;
  return svgDoc(W, H, body);
}

/**
 * Correctness heat-strip: for every (query, scale), does `approach` agree with the
 * case's reference answer? The reference is the hand-written `materialized` baseline
 * (`referenceApproach` on each row records which was actually used), so this reads as
 * "does this pipeline reproduce the answer a human wrote directly against the RDF 1.1
 * data?" — the row that *is* the reference has nothing to compare against and renders
 * as unknown.
 */
function correctness(scheme, engine, approach) {
  const data = rows.filter(r => r.engine === engine && r.scheme === scheme && r.approach === approach);
  const scales = sortScales([ ...new Set(data.map(r => r.scale)) ]);
  const cases = [ ...new Set(data.map(r => r.caseId)) ].sort();
  if (cases.length === 0) {
    return null;
  }
  const cell = 26;
  const padL = 200;
  const padT = 60;
  const W = padL + scales.length * cell + 40;
  const H = padT + cases.length * cell + 20;
  let body = `<text x="${W / 2}" y="24" text-anchor="middle" font-size="16" fill="${COLORS.text}">` +
    `${esc(scheme)} / ${esc(engine)} — ${esc(approach)} vs rewriting-reference agreement</text>`;
  for (const [ j, scale ] of scales.entries()) {
    body += `<text x="${padL + j * cell + cell / 2}" y="${padT - 8}" text-anchor="middle" fill="${COLORS.text}">${esc(scale)}</text>`;
  }
  for (const [ i, caseId ] of cases.entries()) {
    body += `<text x="${padL - 8}" y="${padT + i * cell + cell / 2 + 4}" text-anchor="end" fill="${COLORS.text}">${esc(caseId.split('/').at(-1))}</text>`;
    for (const [ j, scale ] of scales.entries()) {
      const rec = data.find(r => r.caseId === caseId && r.scale === scale);
      let fill = '#eeeeee';
      let mark = '';
      if (rec) {
        // `correct` is null when there is nothing to compare — no reference could be
        // computed for the case, or this row is the reference. That is "unknown", not
        // "wrong", and must render distinctly from an actual mismatch (correct === false).
        if (rec.status === 'error') {
          fill = '#999999';
          mark = '!';
        } else if (rec.status === 'timeout') {
          fill = '#cccccc';
          mark = '…';
        } else if (rec.correct === null) {
          fill = '#7f7f7f';
          mark = '?';
        } else {
          fill = rec.correct ? '#2ca02c' : '#d62728';
          mark = rec.correct ? '✓' : '✗';
        }
      }
      const x = padL + j * cell;
      const y = padT + i * cell;
      body += `<rect x="${x}" y="${y}" width="${cell - 2}" height="${cell - 2}" fill="${fill}">` +
        `<title>${esc(caseId)} @ ${scale}: ${rec ? (rec.error ?? `correct=${rec.correct}, rows=${rec.count}`) : 'n/a'}</title></rect>` +
        `<text x="${x + cell / 2 - 1}" y="${y + cell / 2 + 3}" text-anchor="middle" fill="white">${mark}</text>`;
    }
  }
  return svgDoc(W, H, body);
}

/**
 * The approaches whose answers are checked against the reference (see
 * {@link correctness}). `materialized` is normally the reference itself and so is not
 * among them; every rewriting variant is, `rewriting` included — it is the one this
 * benchmark most needs a verdict on, and it is exactly the one the old
 * `rewriting`-as-its-own-oracle reference could never fail.
 */
const CHECKABLE_APPROACHES = [
  'rewriting',
  'rewriting+removeProjections',
  'rewriting+pushDownAssertions',
  'rewriting+pullUpExtends',
];
/** Filename suffix for each checkable approach's correctness heat-strip. */
const CORRECTNESS_SUFFIX = {
  rewriting: 'rewriting',
  'rewriting+removeProjections': 'proj-removed',
  'rewriting+pushDownAssertions': 'pushdown',
  'rewriting+pullUpExtends': 'pullup',
};

const generators = { time_by_query: timeByQuery, scaling, overhead };
let written = 0;
for (const scheme of schemes) {
  for (const engine of engines) {
    for (const [ name, fn ] of Object.entries(generators)) {
      const svg = fn(scheme, engine);
      if (svg) {
        const path = join(outDir, `${scheme}_${engine}_${name}.svg`);
        writeFileSync(path, svg);
        written++;
        process.stderr.write(`wrote ${path}\n`);
      }
    }
    for (const approach of CHECKABLE_APPROACHES) {
      const svg = correctness(scheme, engine, approach);
      if (svg) {
        const suffix = CORRECTNESS_SUFFIX[approach];
        const path = join(outDir, `${scheme}_${engine}_correctness_${suffix}.svg`);
        writeFileSync(path, svg);
        written++;
        process.stderr.write(`wrote ${path}\n`);
      }
    }
  }
}
process.stderr.write(`\nGenerated ${written} figure(s) in ${outDir}\n`);
